config:
  kubernetes:context: homelab

  pulumi:tags:
    pulumi:template: kubernetes-go

  k8s:installCni: true

  k8s:metallb:
    install: true
    addressPool:
      - 192.168.50.252-192.168.50.254

  k8s:installGatewayApiCrds: true

  k8s:helmCharts:
    - releaseName: metallb
      chart: metallb
      namespace: metallb-system
      repo: "https://metallb.github.io/metallb"
      valuesFile: ""
      version: 0.15.3
    - releaseName: istio
      chart: istiod
      namespace: istio-system
      repo: "https://istio-release.storage.googleapis.com/charts"
      version: 1.29.0
    - releaseName: coredns-external
      chart: coredns
      namespace: coredns
      repo: "https://coredns.github.io/helm"
      valuesFile: ./helm-values/coredns.yaml
      version: 1.45.2
